[package]
name = 'CoinBase'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
BridgeDeployer = '0x0f97d720564154bcb9fab1392f6ff8d4ca9333f6f4ff66a5da8cce493953e645'
ResourceAccountDeployer = '0x6ee56eb2a8e83a89df13189a87e1b9ba1c45aaf150cfc9ebb7b0dcb90431b22b'

