[package]
name = 'Cross'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "89f950b28b2c2f5e270d877160e6007a2d8d25a6" }
Oracle= { local= '../Oracle' }
ResourceAccount= { local= '../ResourceAccount' }
WrappedCoinV1={ local= '../WrappedCoin' }
CoinBase={ local= '../CoinBase' }

[addresses]
BridgeDeployer = '0x786870d087d01714842efcadc56d947ddf4e177ebc9b4fcd8ca546410d8f3d98'
ResourceAccountDeployer = '0xd89c5175dd0f1644b3039a945dcd9bb933958b72f85bc7d70d2b777a355890c0'

