[package]
name = 'Cross'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "a78970aa2a6fd6fa7db94d6d5700a902807102c7" }
Oracle= { local= '../Oracle' }
ResourceAccount= { local= '../ResourceAccount' }
WrappedCoinV1={ local= '../WrappedCoin' }

[addresses]
BridgeDeployer = '0x0fed7b4e9b93c0373998b80cebee85010af2dea9cd5ddc754a01fb89fec291e4'
ResourceAccountDeployer = '0x94bdaffa0d0bfde11de612c640071677c5f68f7721b407f83c738d4c1c05ce7d'

