[package]
name = 'WrappedCoinV1'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "a78970aa2a6fd6fa7db94d6d5700a902807102c7" }

[addresses]
ResourceAccountDeployer = '0x94bdaffa0d0bfde11de612c640071677c5f68f7721b407f83c738d4c1c05ce7d'
