[package]
name = 'aptos-bridge'
version = '1.0.0'
[dependencies.AptosFramework]
local = '/Users/molin/workspace/temp/aptos-core/aptos-move/framework/aptos-framework'
# git = 'https://github.com/davidiw/aptos-core.git'
# rev = 'devnet'
# subdir = 'aptos-move/framework/aptos-framework/'
